- name: Update the NTP server details.
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    line: NTP=10.112.1.1
  notify: Restart_systemd-timesyncd

- name: copy the docker gpg key.
  ansible.builtin.copy:
    src: docker-archive-keyring.gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Copy the pip file.
  ansible.builtin.copy:
    src: pip.conf
    dest: /etc/pip.conf

- name: Copy the docker list file.
  ansible.builtin.copy:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list

- name: Install packages from packages.deb list
  apt:
    name: "{{ packages.deb }}"
    state: present
    update_cache: yes
  tags: packages

